### ISSUE TITLE
AppRegistryNotReady Exception on Django 1.10 Dev

### ISSUE THREAD

**Issue by dacodekid** [Koed00/django-q#164] opened 2016-04-14 14:23 UTC
When running `./manage.py migrate` on `Django 1.10.dev20160413172854`  throws the following exception. But changing to Django 1.9.5 works fine.  Is there any fix to work with `dev` version?

```
╰─$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dacodekid/dev/django/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/dacodekid/dev/django/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/dacodekid/dev/django/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/dacodekid/dev/django/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/dacodekid/dev/django/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/dacodekid/.envs/tradex/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/dacodekid/.envs/tradex/lib/python3.5/site-packages/django_q/__init__.py", line 15, in <module>
    from .tasks import async, schedule, result, result_group, fetch, fetch_group, count_group, delete_group, queue_size
  File "/Users/dacodekid/.envs/tradex/lib/python3.5/site-packages/django_q/tasks.py", line 11, in <module>
    import cluster
  File "/Users/dacodekid/.envs/tradex/lib/python3.5/site-packages/django_q/cluster.py", line 31, in <module>
    import tasks
  File "/Users/dacodekid/.envs/tradex/lib/python3.5/site-packages/django_q/tasks.py", line 13, in <module>
    from django_q.models import Schedule, Task
  File "/Users/dacodekid/.envs/tradex/lib/python3.5/site-packages/django_q/models.py", line 12, in <module>
    class Task(models.Model):
  File "/Users/dacodekid/dev/django/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/dacodekid/dev/django/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/dacodekid/dev/django/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by carltongibson** [comment] 2016-04-14 14:54
I wonder if it's caused by this: 

> ##### Apps registry is no longer auto-populated when unpickling models outside of Django
>
> The apps registry is no longer auto-populated when unpickling models. This was added in Django 1.7.2 as an attempt to allow unpickling models outside of Django, such as in an RQ worker, without calling django.setup(), but it creates the possibility of a deadlock. To adapt your code in the case of RQ, you can [provide your own worker script](http://python-rq.org/docs/workers/) that calls django.setup().
>
> — [Django 1.10 Release Notes](https://docs.djangoproject.com/en/dev/releases/1.10/#apps-registry-is-no-longer-auto-populated-when-unpickling-models-outside-of-django)

**Comment by Koed00** [comment] 2016-04-14 19:10
I'll try to have a look at this in the weekend. 
@carltongibson is probably right, but I need to make sure it doesn't break compatibility with the older Django versions. I try to to support the last two major (released) versions of Django.

**Comment by Koed00** [comment] 2016-04-24 13:27
I'm going to postpone this until the 1.10 alpha is released in about two weeks.

**Comment by techdragon** [comment] 2016-05-15 08:15
I've just run into this with a Django 1.9.6 site, so this doesn't appear to be just a 1.10.x issue.

**Comment by Koed00** [comment] 2016-05-15 09:34
I've updated the tests to 1.9.6. I wouldn't be the first time that some of Django's next releases code ended up in an earlier version through a bugfix. 
Still a bit until the 1.10 alpha is released and I can start testing that.

**Comment by Koed00** [comment] 2016-06-07 15:21
It turned out to be a problem with the code that makes Django 1.8 and lower work.
I've adjusted the code to allow for 1.10 versions.
Also optparse is now deprecated, so I replaced that with argparse for the commands.

Should work on 1.10a1. Tests are passing on Travis.

**Comment by thinkwelltwd** [comment] 2016-06-22 20:42
> It turned out to be a problem with the code that makes Django 1.8 and lower work.

Does your fix still allow Django 1.8 to work? I have to be on the LTS till the next LTS release.

**Comment by Eagllus** [comment] 2018-02-06 10:26
Could this issue be closed? It's been around 1,5 years sinds the last post?

**Comment by Eagllus** [comment] 2018-02-06 14:44
@thinkwelltwd could you confirm that this issue can be closed?

**Comment by thinkwelltwd** [comment] 2018-02-07 01:30
Yes it can as far as I know. I'm now on 1.11 so I'm not using older versions.

**Closed** 2018-02-07 07:34 UTC
